- id: 10.1038/s41587-022-01209-1
  image: images/paper_image/cospar.png
  date: 2022-2-21
  extra-links:
    - type: pdf
      link: pdfs/cospar.pdf
    - type: website
      link: https://cospar.readthedocs.io/en/latest/
    - type: source
      link: https://github.com/AllonKleinLab/cospar
  tags:
    - Lineage tracing, cell fate prediction, trajectory inference
