- id: 10.1038/s41587-022-01209-1
  image: https://user-images.githubusercontent.com/4595786/104988296-b987ce00-59e5-11eb-8dbe-a463b355a9fd.png
  date: 2022-2-21
  extra-links:
    - type: pdf
      link: pdfs/cospar.pdf
    - type: website
      link: https://cospar.readthedocs.io/en/latest/
    - type: source
      link: https://github.com/AllonKleinLab/cospar
  tags:
    - Lineage tracing, cell fate prediction, trajectory inference
