- id: 10.1038/s41587-022-01209-1
  image: images/paper_image/cospar.png
  date: 2022-2-21
  extra-links:
    - type: source
      link: pdfs/cospar.pdf
      text: pdf
    - type: website
      link: https://cospar.readthedocs.io/en/latest/
      text: Documentation
    - type: source
      link: https://github.com/AllonKleinLab/cospar
      text: Code
  tags:
    - Lineage tracing, cell fate prediction, trajectory inference

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  extra-links:
    - type: preprint
      link: https://doi.org/10.7287/peerj.preprints.3100v1
    - type: manubot
      link: https://greenelab.github.io/scihub-manuscript/
    - type: source
      link: https://github.com/greenelab/scihub-manuscript
      text: Manuscript source
    - type: source
      link: https://github.com/greenelab/scihub
      text: Analyses source
